name: Ultimate Splinterlands Bot V2

on:
  push:
    branches: [ "master" ]

jobs:

  build:

    strategy:
      matrix:
        configuration: [Release]

    runs-on: windows-latest  

    env:
      Solution_Name: Ultimate Splinterlands Bot V2.sln
      
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Install .NET Core
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
 
    - name: Build USB
      run: dotnet build --configuration Release
      env:
        DOTNET_CLI_TELEMETRY_OPTOUT: true
     
    - name: Upload USB
      uses: actions/upload-artifact@v3
      with:
        name: USB
        path: ./bin/Release/net6.0/
